### ISSUE TITLE
Naming: What is the name of this group?

### ISSUE THREAD

**Issue by jonathanrobie** [biblicalhumanities/copenhagen-alliance#6]
The minutes suggest this name as one possibility: 

> Copenhagen Alliance for Open Biblical Language Resources

Do we want to adopt that name?  Are there others we should consider?

**Comment by codykingham** [comment]
I like the name, though the acronym is kind of lame: CAOBLR

**Comment by jonathanrobie** [comment]
COBLAR (pronounced "cobbler") or even CABLOR would be better as an acronym, but I can't get the phrase to cooperate.

Perhaps we would call ourselves the Copenhagen Alliance for short anyway, rather than use an acronym?

**Comment by jonathanrobie** [comment]
Proposal:  The name will be "Copenhagen Alliance for Open Biblical Language Resources".  Instead of using an acronym, we will use the short name "Copenhagen Alliance".

Please indicate your vote using a 👍 or 👎.  The vote will be counted on Friday.  If the vote is conclusive, we will close this issue then.

**Comment by johanovic** [comment]
I am wondering whether the Copenhagen bit is relevant. It made sense while we were in Copenhagen, but now it has lost its value...

**Comment by jonathanrobie** [comment]
> I am wondering whether the Copenhagen bit is relevant. It made sense while we were in Copenhagen, but now it has lost its value...

Do you have an alternative name?  At the meeting, most people in the room really seemed to want the name to have Copenhagen in it.

**Comment by jtauber** [comment]
I love having the name "Copenhagen" in it and there's quite a tradition of naming alliances after the cities where they first were made, whether in politics or technology.

**Comment by jtauber** [comment]
I also really like "Copenhagen Alliance" as the shortening rather than an acronym.

**Comment by rdeblois1960** [comment]
Yes, I also like Copenhagen Alliance. It has a good ring to it.

**Comment by johanovic** [comment]
Alright, you have convinced me :)

**Comment by johanovic** [comment]
Another quick comment to remind ourselves that we should also share this thread via email, not only slack. Many of the people in Copenhagen have never used slack.

**Comment by jonathanrobie** [comment]
> Another quick comment to remind ourselves that we should also share this thread via email, not only slack. Many of the people in Copenhagen have never used slack.

I'll ask Judith to send mail on this.

**Comment by ernstboogert** [comment]
I like both the name and the shortening: the 'openness' of the community is clearly present in 'Alliance' and 'Open...'

**Comment by jonathanrobie** [comment]
> Proposal:  The name will be "Copenhagen Alliance for Open  Biblical Language Resources".  Instead of using an acronym, we will use  the short name "Copenhagen Alliance".

In https://github.com/biblicalhumanities/copenhagen-alliance/issues/6#issuecomment-376635031, 11 people voted in favor, there were no other votes. We will adopt this name.
